host: 127.0.0.1
port: 8892
isdebug: False
use_gpu: False
check_possible_combinations: True
#possible_combinations_table: /media/grartem/B7DB5B36121B73AA/Projects/RobotCommandParser_service/Data/possible_combinations_of_attributes_for_actions.csv
possible_combinations_table: /home/elnmax/arctic_build/RobotCommandParser_service/Data/possible_combinations_of_attributes_for_actions.csv
Model:
  model_type: bert
  model_path: /home/elnmax/arctic_build/RobotCommandParser_service/Models/Classifier/MyMultiTiny2_data6
  num_sublabels_per_biglabel: [15, 9, 13, 25, 25, 17, 2, 10, 15, 10, 15, 9, 2]
  add_attention_for_labels: False
  target_labels: ["action", "direction", "meters", "degs", "hours", "object1", "nearest", "relation1", "object2", "relation2", "object3", "self", "gaze"]