host: 127.0.0.1
port: 8891
isdebug: False
use_coreference: True
classifier_url: http://127.0.0.1:8892/classify_phrases
#coreference_url: http://127.0.0.1:8893
splitter_url: http://127.0.0.1:8896/split_commands
gapping_url: http://127.0.0.1:8893/gapping
