host: 127.0.0.1
port: 8896
isdebug: False
use_gpu: False
Model:
  model_type: bert
  model_path: /media/grartem/B7DB5B36121B73AA/Projects/RobotCommandParser_service/Models/Splitter/TokenCLS_sepPredictor_ipynb_Copy1_data3v2
  labels: ["[CMD]", "[SEP]","O"]